apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-dev
  labels:
    app: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: backend
        image: chandrasekharreddyk/mern-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service.mern-dev.svc.cluster.local:27017/mernapp"