apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-dev
  labels:
    app: mern-backend
spec:
  type: ClusterIP
  selector:
    app: mern-backend
  ports:
  - port: 5000
    targetPort: 5000