apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mern-dev
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017